---
services:
  hugo-server:
    image: hugomods/hugo:0.146.7
    command: "hugo server --buildFuture --buildDrafts --bind=0.0.0.0"
    volumes:
      - "../..:/src"
      - ~/hugo_cache:/tmp/hugo_cache
    ports:
      - "1313:1313"
      
